/**
 * Shared formatting utilities for o8.
 */

export function formatModelLabel(model: string): string {
  // The built-in agent's receipt ids, matched whole.
  if (model === 'o8-free') return 'o8';
  if (model === 'pi') return 'Pi';
  return model
    // Vendor-prefixed model ids from runtime and config surfaces
    .replace('openai-codex/gpt-6.1-sol', 'Codex GPT-6.1 Sol')
    .replace('openai-codex/gpt-6-astra', 'Codex GPT-6 Astra')
    .replace('openai-codex/gpt-6-sol', 'Codex GPT-6 Sol')
    .replace('openai-codex/gpt-6-luna', 'Codex GPT-6 Luna')
    .replace('openai-codex/gpt-5.6-sol', 'Codex 5.6 Sol')
    .replace('openai-codex/gpt-5.6-terra', 'Codex 5.6 Terra')
    .replace('openai-codex/gpt-5.6-luna', 'Codex 5.6 Luna')
    .replace('openai-codex/gpt-5.5', 'Codex 5.5')
    .replace('openai-codex/gpt-5.4', 'Codex 5.4')
    .replace('openai-codex/gpt-5.3-codex', 'Codex 5.3')
    .replace('anthropic/claude-fable-5-1', 'Fable 5.1')
    .replace('anthropic/claude-opus-5-5', 'Opus 5.5')
    .replace('anthropic/claude-fable-5[1m]', 'Fable 5 (1M)')
    .replace('anthropic/claude-fable-5', 'Fable 5')
    .replace('anthropic/claude-opus-5', 'Opus 5')
    .replace('anthropic/claude-opus-4-8', 'Opus 4.8')
    .replace('anthropic/claude-opus-4-7', 'Opus 4.7')
    .replace('anthropic/claude-opus-4-6', 'Opus 4.6')
    .replace('anthropic/claude-sonnet-5', 'Sonnet 5')
    .replace('anthropic/claude-sonnet-4-6', 'Sonnet 4.6')
    .replace('anthropic/claude-sonnet-4-5-20250929', 'Sonnet 4.5')
    .replace('anthropic/claude-sonnet-4-20250514', 'Sonnet 4')
    .replace('anthropic/claude-haiku-4-5-20251001', 'Haiku 4.5')
    .replace('google/gemini-3-flash-preview', 'Gemini 3 Flash')
    // Bare forms (from live sessions)
    .replace('gpt-6.1-sol', 'GPT-6.1 Sol')
    .replace('gpt-6-astra', 'GPT-6 Astra')
    .replace('gpt-6-sol', 'GPT-6 Sol')
    .replace('gpt-6-luna', 'GPT-6 Luna')
    .replace('gpt-5.6-sol', 'GPT-5.6 Sol')
    .replace('gpt-5.6-terra', 'GPT-5.6 Terra')
    .replace('gpt-5.6-luna', 'GPT-5.6 Luna')
    .replace('gpt-5.5', 'GPT-5.5')
    .replace('gpt-5.4', 'GPT-5.4')
    .replace('gpt-5.3-codex', 'Codex 5.3')
    .replace('claude-fable-5-1', 'Fable 5.1')
    .replace('claude-opus-5-5', 'Opus 5.5')
    .replace('claude-fable-5[1m]', 'Fable 5 (1M)')
    .replace('claude-fable-5', 'Fable 5')
    .replace('claude-opus-5', 'Opus 5')
    .replace('claude-opus-4-8', 'Opus 4.8')
    .replace('claude-opus-4-7', 'Opus 4.7')
    .replace('claude-opus-4-6', 'Opus 4.6')
    .replace('claude-sonnet-5', 'Sonnet 5')
    .replace('claude-sonnet-4-6', 'Sonnet 4.6')
    .replace('claude-sonnet-4-20250514', 'Sonnet 4')
    .replace('claude-haiku-4-5-20251001', 'Haiku 4.5')
    .replace('gemini-3-flash-preview', 'Gemini 3 Flash')
    .replace('gemini-3.1-pro-preview', 'Gemini 3.1 Pro')
    .replace('gemini-3-pro-preview', 'Gemini 3 Pro')
    .replace('gemini-2.5-pro', 'Gemini 2.5 Pro')
    .replace('gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite')
    .replace('gemini-2.5-flash', 'Gemini 2.5 Flash')
    .replace('grok-4.5', 'Grok 4.5')
    .replace('codex owned', 'Codex')
    .replace(/^openai-codex\//, '')
    .replace(/^anthropic\//, '')
    .replace(/^google\//, '');
}
