import { useEffect, useRef, useState } from 'react';
import { takeDesignFrames } from '@/lib/motion/js-cadence';
import { DESIGN_FRAME_MS } from '@/lib/motion/pipeline';

/**
 * Advance the reveal index, then extend to the next whitespace so whole WORDS
 * appear instead of splitting mid-word.
 *
 * Two goals in tension — FAST and SMOOTH — balanced by a proportional step with
 * a ceiling. Orchestrator replies usually arrive as one big buffered chunk (the
 * reply is already fully generated by the time the first byte hits the client),
 * so the reveal is largely cosmetic: it must make a done answer feel like fast
 * live streaming, not "the answer is ready but it's slowly typing it out." So
 * step = 20% of the remaining backlog (drains a big chunk quickly) capped at 32
 * chars per 60 Hz design frame (~1900 chars/s) — fast, but still a continuous stream,
 * never the front-loaded 185/145/115-char spike that read as "shooting in". The
 * proportional term also means a genuinely incremental backend stream is matched
 * gently (small backlog → small step), and it eases the last ~160 chars to a
 * soft stop. Time-to-first-token is unaffected: the very first frame already
 * reveals a step's worth, so text appears the instant the chunk lands. Pure +
 * synchronous so it's unit-testable without rAF.
 */
export function advanceRevealByDesignFrames(current: number, text: string, frames: number): number {
  let index = current;
  const count = Number.isFinite(frames) ? Math.max(0, Math.floor(frames)) : 0;
  for (let step = 0; step < count && index < text.length; step += 1) {
    index = nextRevealIndex(index, text);
  }
  return index;
}

export function nextRevealIndex(current: number, text: string): number {
  const len = text.length;
  if (current >= len) return len;
  const remaining = len - current;
  const step = Math.min(32, Math.max(4, Math.ceil(remaining * 0.2)));
  let next = Math.min(len, current + step);
  // Extend to the next whitespace so whole words appear — but cap the search so
  // a giant unbroken token (URL, base64 blob) can't dump in a single frame.
  const cap = next + 10;
  while (next < len && next < cap && !/\s/.test(text[next]!)) next += 1;
  return next;
}

function prefersReducedMotion(): boolean {
  if (typeof window === 'undefined' || !window.matchMedia) return false;
  return window.matchMedia('(prefers-reduced-motion: reduce)').matches;
}

/**
 * Smoothly reveal streaming text instead of dumping each network burst.
 *
 * While `streaming`, the returned text catches up to `text` a few chars per
 * animation frame (snapped to word boundaries), giving a steady typewriter feel
 * no matter how bursty the deltas arrive — the orchestrator backend often sends
 * whole lines/paragraphs in one event, which used to pop in as jarring chunks.
 * When not streaming (history, or the turn finished) the full text shows
 * immediately, and reduced-motion users always get it instantly.
 *
 * The rAF loop self-stops when caught up and restarts on the next burst (no idle
 * churn between deltas), and reads the target via a ref so it never streams a
 * stale closure's text. Reveal speed is locked to a 60 Hz design cadence so a
 * 120/240/540 Hz panel cannot 2–9× the React commit rate.
 */
export function useSmoothText(text: string, streaming: boolean): string {
  const reduced = prefersReducedMotion();
  // Once a message has streamed, keep PACING the leftover tail even after
  // `streaming` flips false — the orchestrator often ends a turn (status→ready)
  // while the reveal is still catching up to a big one-shot reply, and snapping
  // the remainder in a single frame is exactly the end-of-turn burst we're
  // avoiding. So animate on (streaming OR ever-streamed); the loop drains to the
  // end and then settles. A never-streamed history message shows full at once.
  const everStreamedRef = useRef(false);
  const animate = (streaming || everStreamedRef.current) && !reduced;
  const [revealed, setRevealed] = useState(animate ? 0 : text.length);
  const idxRef = useRef(animate ? 0 : text.length);
  const targetRef = useRef(text);
  targetRef.current = text;
  const rafRef = useRef<number | null>(null);
  const runningRef = useRef(false);
  const accRef = useRef(0);
  const lastTsRef = useRef<number | null>(null);

  useEffect(() => {
    if (streaming) everStreamedRef.current = true;
  }, [streaming]);

  // Not animating (history / reduced-motion) → show everything now.
  useEffect(() => {
    if (animate) return;
    if (rafRef.current != null) { cancelAnimationFrame(rafRef.current); rafRef.current = null; }
    runningRef.current = false;
    accRef.current = 0;
    lastTsRef.current = null;
    idxRef.current = targetRef.current.length;
    setRevealed(targetRef.current.length);
  }, [animate, text]);

  // Drive the reveal. Re-runs whenever `text` grows (a new burst) or `streaming`
  // ends (drain the tail); the loop self-stops when caught up and the next burst
  // restarts it. Reads target via ref → no stale closure.
  useEffect(() => {
    if (!animate) return;
    if (idxRef.current > targetRef.current.length) {
      idxRef.current = 0;
      setRevealed(0);
      accRef.current = 0;
      lastTsRef.current = null;
    }
    const tick = (ts: number) => {
      const last = lastTsRef.current;
      lastTsRef.current = ts;
      const dt = last == null ? DESIGN_FRAME_MS : ts - last;
      const taken = takeDesignFrames(accRef.current, dt);
      accRef.current = taken.remainderMs;
      if (taken.frames > 0) {
        const next = advanceRevealByDesignFrames(idxRef.current, targetRef.current, taken.frames);
        idxRef.current = next;
        setRevealed(next);
      }
      if (idxRef.current < targetRef.current.length) {
        rafRef.current = requestAnimationFrame(tick);
      } else {
        runningRef.current = false;
        rafRef.current = null;
      }
    };
    if (!runningRef.current && idxRef.current < targetRef.current.length) {
      runningRef.current = true;
      lastTsRef.current = null;
      rafRef.current = requestAnimationFrame(tick);
    }
  }, [animate, text, streaming]);

  useEffect(() => () => {
    if (rafRef.current != null) cancelAnimationFrame(rafRef.current);
    rafRef.current = null;
    runningRef.current = false;
    accRef.current = 0;
    lastTsRef.current = null;
  }, []);

  return animate ? targetRef.current.slice(0, revealed) : text;
}
